theme: jekyll-theme-minimal
title: Cole Baxendale's E-Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome website hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
